
// USERS
export const INITIAL_USER_SUCCESS = 'INITIAL_USER_SUCCESS';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';


//PICTURES

export const GET_PICTURES_SUCCESS = 'GET_PICTURES_SUCCESS';
export const GET_USER_PICTURES_SUCCESS = 'GET_USER_PICTURES_SUCCESS';